project_id = "mlmjlgmsrkemsuwdohsa"

[functions.process-signature]
verify_jwt = false

[functions.send-signing-email]
verify_jwt = false

[functions.send-signed-notification]
verify_jwt = false

[functions.process-intake-document]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.trigger-make-scenario]
verify_jwt = false

[functions.receive-make-webhook]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-update-role]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-approve-user]
verify_jwt = true

[functions.receive-sponsorship-application]
verify_jwt = false

[functions.receive-volunteer-application]
verify_jwt = false
