import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
export function useProposalCollaboration(grantId?:string){const qc=useQueryClient();const invalidate=()=>qc.invalidateQueries({queryKey:["proposal-collaboration"]});
 const grants=useQuery({queryKey:["proposal-collaboration","grants"],queryFn:async()=>{const{data,error}=await(supabase as any).from("grant_applications").select("id,title,stage,ngo_id,department_contributions_json,ngos(legal_name,common_name)").order("created_at",{ascending:false});if(error)throw error;return data??[];}});
 const contributions=useQuery({queryKey:["proposal-collaboration","contributions",grantId],enabled:Boolean(grantId),queryFn:async()=>{const{data,error}=await(supabase as any).from("grant_proposal_contributions").select("*").eq("grant_application_id",grantId).order("created_at",{ascending:false});if(error)throw error;return data??[];}});
 const submit=useMutation({mutationFn:async(input:{department:string;sectionKey:string;title:string;content:string})=>{const{data,error}=await(supabase as any).rpc("submit_grant_proposal_contribution",{p_grant_application_id:grantId,p_department:input.department,p_section_key:input.sectionKey,p_section_title:input.title,p_content_markdown:input.content,p_source_analysis_run_id:null,p_source_recommendation_ids:[]});if(error)throw error;return data;},onSuccess:()=>{invalidate();toast.success("Department contribution submitted");},onError:(e:Error)=>toast.error(e.message)});
 const review=useMutation({mutationFn:async({id,decision,notes}:{id:string;decision:string;notes?:string})=>{const{data,error}=await(supabase as any).rpc("review_grant_proposal_contribution",{p_contribution_id:id,p_decision:decision,p_notes:notes||null});if(error)throw error;return data;},onSuccess:invalidate,onError:(e:Error)=>toast.error(e.message)});
 const assemble=useMutation({mutationFn:async()=>{const{data,error}=await(supabase as any).rpc("assemble_grant_proposal_contributions",{p_grant_application_id:grantId});if(error)throw error;return data;},onSuccess:()=>{invalidate();toast.success("Approved department sections assembled");},onError:(e:Error)=>toast.error(e.message)});
 return{grants,contributions,submit,review,assemble};}
