import { useMemo, useState } from "react";
import { format, startOfYear } from "date-fns";
import { MainLayout } from "@/components/layout/MainLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { BarChart3, Loader2, Send, Share2 } from "lucide-react";
import { useWorkspaceNgo } from "@/hooks/useWorkspaceNgo";
import { useFinanceAnalysisCenter } from "@/hooks/useFinanceAnalysisCenter";

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
export default function FinanceAnalysisCenterPage(){
  const{selectedNgo,selectedNgoId}=useWorkspaceNgo();const center=useFinanceAnalysisCenter(selectedNgoId);
  const[period,setPeriod]=useState({start:format(startOfYear(new Date()),"yyyy-MM-dd"),end:format(new Date(),"yyyy-MM-dd"),scenario:"base"});
  const[grantId,setGrantId]=useState("");const[content,setContent]=useState("");
  const latest=center.runs.data?.[0];const metrics=latest?.metrics_json||{};const recs=center.recommendations.data??[];
  const generated=useMemo(()=>`## Financial Capacity and Budget\n\nFor the analyzed period, the organization recorded revenue of ${money.format(Number(metrics.revenue||0))}, expenses of ${money.format(Number(metrics.expenses||0))}, and an operating margin of ${money.format(Number(metrics.operating_margin||0))}. Available cash was ${money.format(Number(metrics.cash||0))}, representing approximately ${metrics.cash_runway_months??"—"} months of average operating expenses.\n\nThe proposed grant budget will use the HPG-approved chart of accounts and will be monitored through quarterly balanced-ledger submissions.`,[metrics]);
  if(!selectedNgoId)return <MainLayout title="Financial Analysis Center"><Card><CardContent className="p-8 text-sm text-muted-foreground">Select an NGO to analyze.</CardContent></Card></MainLayout>;
  return <MainLayout title="Financial Analysis & Forecasting" subtitle={`${selectedNgo?.common_name||selectedNgo?.legal_name}: live ledger analysis, NGO recommendations, and grant-proposal finance content.`}><div className="space-y-6">
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5"/>Run analysis</CardTitle></CardHeader><CardContent className="flex flex-wrap items-end gap-3"><div className="space-y-2"><Label>Start</Label><Input type="date" value={period.start} onChange={e=>setPeriod({...period,start:e.target.value})}/></div><div className="space-y-2"><Label>End</Label><Input type="date" value={period.end} onChange={e=>setPeriod({...period,end:e.target.value})}/></div><div className="space-y-2"><Label>Scenario</Label><Select value={period.scenario} onValueChange={value=>setPeriod({...period,scenario:value})}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent>{["base","conservative","growth","stress"].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><Button disabled={center.run.isPending} onClick={()=>center.run.mutate(period)}>{center.run.isPending&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Analyze live ledger</Button></CardContent></Card>
    {latest&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Revenue",metrics.revenue],["Expenses",metrics.expenses],["Operating margin",metrics.operating_margin],["Cash runway",`${metrics.cash_runway_months??"—"} months`]].map(([label,value])=><Card key={String(label)}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{typeof value==="number"?money.format(value):value}</p></CardContent></Card>)}</div>}
    <Card><CardHeader><CardTitle>Recommendations</CardTitle><CardDescription>Finance reviews each recommendation before sharing it in the NGO portal.</CardDescription></CardHeader><CardContent className="space-y-3">{recs.length===0?<p className="text-sm text-muted-foreground">Run an analysis to generate recommendations.</p>:recs.map((rec:any)=><div key={rec.id} className="rounded-md border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{rec.title}</p><p className="mt-1 text-sm text-muted-foreground">{rec.summary}</p></div><div className="flex items-center gap-2"><Badge variant={rec.priority==="critical"?"destructive":"secondary"}>{rec.priority}</Badge><Badge>{rec.status.replaceAll("_"," ")}</Badge></div></div>{["draft","internal_review"].includes(rec.status)&&<Button className="mt-3" size="sm" variant="outline" onClick={()=>center.share.mutate(rec.id)}><Share2 className="mr-2 h-4 w-4"/>Share with NGO</Button>}</div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Send Finance section to Development</CardTitle><CardDescription>The approved financial analysis becomes the Finance-owned portion of the selected NGO grant proposal.</CardDescription></CardHeader><CardContent className="space-y-4"><Select value={grantId} onValueChange={setGrantId}><SelectTrigger><SelectValue placeholder="Select NGO grant proposal"/></SelectTrigger><SelectContent>{(center.grants.data??[]).map((grant:any)=><SelectItem key={grant.id} value={grant.id}>{grant.title} · {grant.stage}</SelectItem>)}</SelectContent></Select><Textarea className="min-h-56" value={content||generated} onChange={e=>setContent(e.target.value)}/><Button disabled={!grantId||center.contribute.isPending} onClick={()=>center.contribute.mutate({grantId,title:"Financial Capacity and Budget",content:content||generated,analysisRunId:latest?.id,recommendationIds:recs.map((r:any)=>r.id)})}><Send className="mr-2 h-4 w-4"/>Submit Finance contribution</Button></CardContent></Card>
  </div></MainLayout>;
}
